modLoader = "javafml"
loaderVersion = "[40,)"
license = "All rights reserved"
issueTrackerURL = "https://www.curseforge.com/minecraft/mc-mods/watercore/issues"


[[mods]]
modId = "watercore"
version = "${file.jarVersion}"
displayName = "WATERCoRE"
logoFile = "pack.png"
credits = "SrRapero720 | WATERCoRE"
authors = "SrRapero720"
description = '''
WATERCoRE, Tu herramienta de servidores (oficial de WATERMiNE) Integracion oficial de Dimensiones, posiones, monedas y otras cosas.
'''


[[dependencies.watercore]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.watercore]]
modId = "luckperms"
mandatory = false
versionRange = "[5.4,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.watercore]]
modId = "create"
mandatory = false
versionRange = "[0.5,)"
ordering = "NONE"
side = "BOTH"
