modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/watercore/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="watercore" #mandatory
version="${file.jarVersion}" #mandatory
displayName="WATERCoRE" #mandatory
logoFile="" #optional
credits="SrRapero720 | WATERCoRE" #optional
authors="SrRapero720" #optional
description='''
WATERCoRE, Tu herramienta de servidores (oficial de WATERMiNE)
Integracion oficial de Dimensiones, posiones, monedas y otras cosas.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.watercore]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[40.2,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.watercore]]
modId="create"
mandatory=false
versionRange="[0.5,)"
ordering="NONE"
side="BOTH"
