modLoader = "javafml"
loaderVersion = "${fgloaderrange}"
license = "${modlicense}"
issueTrackerURL = "https://github.com/${github_project}/issues"

[[mods]]
    modId="${modid}"
    version="${modversion}"
    displayName="${modname}"
    logoFile="pack.png" #optional
    displayURL="https://www.curseforge.com/minecraft/mc-mods/watercore" #optional
    authors="${modauthor}" #optional
    credits="${modcredits}" #optional
    displayTest="MATCH_VERSION"
    clientSideO1nly=true
    description = '''${mod_description}'''

[[dependencies.${modid}]]
    modId = "forge"
    mandatory = true
    versionRange = "[40,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.watercore]]
    modId = "luckperms"
    mandatory = false
    versionRange = "[5.4,)"
    ordering = "NONE"
    side = "SERVER"

[[dependencies.watercore]]
    modId = "create"
    mandatory = false
    versionRange = "[0.5,)"
    ordering = "NONE"
    side = "BOTH"
